= Dapeng VR Crisis

关于乐相的问题，由于时间比较紧，我在这里先给个简单的项目实施指导。

首先需要明确的是：我们的目标是构建双方良好的合作信任关系，实现长期的商业捆绑，最好是排他性的合作，从而稳固我们的长期利益。“合作信任关系”是关键，没有这个为前提，换掉你的SDK是弹指一挥的事儿。所以不要机械的一味追求SDK集成。

当前需要处理的是2个方面的问题：
1. 集成的问题
2. 客户满意度的问题

目前来看，客户的满意度上有点问题，主要是几次集成失败带来的。然后会提出一些各种质疑，有版本号吗？文档怎么没有？归根结底的质疑是你们系统成熟吗？然后大家可能有点心虚，觉得我们这两天每天出版本，好像很不成熟啊。嘴上说我们很成熟，其实心很虚，说成熟都很假。

所以我要告诉大家软件业的几个事实：

第一，传统软件开发用的瀑布模型，从计划、开发、测试到上线发布是以年为单位的，这就是你们看到Windows,Oracle这些软件大厂都是几年出个版本，几千人做的软件，发布了还要先内测个几个月、公测个几个月、beta1到betaN都是一大把。Linux，开源和互联网把游戏规则改变了，今天大部分企业都没这么干的，每天出版本快速迭代是常态，这叫不成熟吗？这叫Agile，敏捷开发，要成熟的找微软去，就连微软也不这么干了，猛拥抱开源社区，全世界都在用敏捷开发走快速迭代。如果说相对成熟度，我们的VRAD系统肯定比国内很多VR厂商的系统成熟，毕竟做了也有1年了，现在这个OpenGL的版本是根据客户需求临时订制的，但技术体系和架构肯定是成熟的，我们的核心开发人员在业界来看也算是比较牛吧，以后找时间应该把他们的精彩作品翻出来秀一秀。

第二，Andriod是个高度碎片化的生态系统，从软件到硬件都可以订制，各家有各家的订制版本，全世界几百个不同的订制。PC或者Mac的兼容性是经过几十年产业整合后的结果，这年头很少见到同一个操作系统同版本下软件不兼容的情况，早期8088时代，兼容芯片导致程序崩溃很常见，硬件不兼容导致的问题很正常。今天手机芯片的不同，操作系统的版本不同引起的软件故障也是很常见的，尤其是二进制代码，字节码程序会好一些但仍然也会出问题。今天手游公司花1个月做几十个Andriod机型适配是很常见的事情，前几年非智能机时代，手游公司花几个月做上百个机型适配更是业界常态，今天VR设备也面临同样的问题，所以做设备适配性调试是很正常的，各家设备芯片用的都不一样，OS也不一样，不做适配怎么支持？除非你用的是Google的设备和Google官方的Android版本。

所以我们当先是需要对客户的自家设备做适配性的调试，调试了3次都有问题，很正常，程序员调试程序调试几百次不也是很常见的吗？问题是谁来做？怎么做？什么心态做？

抛开适配性不说，谁能写程序一次编译通过？我过去20年来从来没听说过。你知道的话可以告诉我。所以先保持一个正确心态，当然正确心态需要有个对技术工作的正确认识。否则就不适合做这行。

适配工作谁来做的问题需要双方协商，如果我们能拿到设备，当然可以由我们来做，我觉得有必要对方提供一个设备供我们调试.从Oculus到PlayStation，开发专用设备软件不可能只在模拟器里面跑的，除非你是做着玩。出产品一样要有真机调试，这是最终的解决办法。如果时间紧迫，等设备快递的同时，双方也可以协商现在这种模式，就是耦合度比较高，迭代比较慢，不推荐。

总结下来：

解决1.集成的问题，需要乐相提供调试设备
解决2.客户满意度的问题，需要跟客户充分沟通，有理有据的说服对方配合，不要慌。

此外的其它建议：
1. 双方需要充分沟通技术现状，不要急着催进度，搞清楚问题和解决问题的方法后双方摆正心态的去协作配合。
2. 重新进行技术评估来商讨可行的时间表
3. 最终需要达到前面说的“合作信任关系”的目的，需要在上下各个层面进行全面沟通和理解才能实现，需要在高层做工作但是需要支持的也及时反馈，呼叫火力支援，我们是一个团队，大家并肩作战。

兄弟们，加油。
