= 一个人的发展空间在哪里

# 一个人的发展空间在哪里

## 方向比智力更重要

一个人的发展空间主要看两点：做什么事，和谁做。

做什么事的背后是选方向，正常人的智力差别在50%以内，但是成就可能差1万倍，差别就在于方向。
和谁做也很关键，跟不靠谱的人合作是没戏的，靠不靠谱这事儿跟学历、技能、职位的关系都不是很大，Jobs当年找百事可乐CEO合作后，结果把自己赶出了苹果。

选方向可能比较困难一些，了解一个人也不太容易。那怎么办？

根据我的观察，一个显而易见的事实是：
所有成功公司的前20名员工坚持下来的都获得了巨大成功。

是的，包括那个蠢萌的产品经理。o_0

最聪明的一群人在微软开发IE浏览器是不会有机会成为Google或Facebook的前20名员工的。

因此一个简单的成功策略就是：

－ 找一家高速成长的小公司
－ 成为前20名员工

记住一定要小，大了就没有成长性了。婴儿可以3个月体重翻倍，我现在体重不减就不错了。

如果你还想把握更多的细节，可以接着往下看。


## 未来最有前途的方向

最有前途的方向都在革命性｀方法｀周围。

15年前，最有革命性的方法是｀Google｀，颠覆了｀Yahoo！｀这种方法领导的传统互联网，改变了人类的工作方式。

现在，最有革命性的方法是｀移动｀，它改变了人类的生活方式。

在这个｀方法｀周围，诞生了一堆颠覆性产品，微信颠覆了传统通讯业、手游颠覆了传统游戏业、甚至传统互联网本身都被｀移动｀颠覆了。

但这都是过去了，我们更关注的是明天的走势，抛还是不抛，这是个问题。

前面比较好理解，因为你身在其中，但是假如150年前（1866）的人乘坐时光机器来到现在一看多半会被今天这个世界吓尿了。人类发展速度快的“难以理解”，为什么“难以理解”，因为绝大部分人的学习速度赶不上人类的发展速度，所以你会发现上一代很难理解你为什么玩游戏、为什么网购、为什么出门就有车等着你。

同样，未来也一样“难以理解”，所以下面的内容使劲“理解”一下。

未来一个革命性的领域会跟大数据和云计算有关，大数据和云计算本身没什么新鲜的，但是量变会带来质变。

云计算是工具、大数据是原料，最终天文数量级的数据在云计算中发生“核聚变”，产生一系列惊人的产品。

－ 比人类更聪明的人工智能
－ 人机合体
－ 生命打印机

这个革命性的｀方法｀权且称之为｀超级智能｀，现在人类正在朝那个方向上加速前进。这次文明的进化在科技灾难片“终结者”和“Matrix”系列中有具体描绘（灾难片一般票房比较好）。

仅去年一年就有超过14亿（IDC数据）部智能手机走下生产线接入互联网，很快这个数字还会加倍，汽车、电视、冰箱甚至路灯都会变得“智能”并接入互联网。

所有跟大数据和云计算的相关的领域都会极大发展。或者说所有产业都会被云计算和大数据改造。


## 怎么把握机会

满足需求就可以了。

人们要吃喝水，供水就好了，无论是矿泉水还是自来水。
增加技术含量？可口可乐。

未来那个｀超级智能｀对大数据和云计算也很饥渴。

那我该怎么做？
在你的理解能力极限下找一家最符合这个方向的小公司加入。



## 这里有一个机会

我和我的团队目前在开发大数据和云计算相关产品。
我们的业务在高速成长。
最重要的是我们不到20人 o‿-


如果你自信是个人才，给我写信。
blackgun99+github@gmail.com



